version: 2.1

jobs:
  lint-app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container for each microservices
          command: |
            echo "--------- The images is Building ------------"
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed nweke/udagram-api-feed:v1
            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user nweke/udagram-api-user:v1

            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend nweke/udagram-frontend:v1
            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy nweke/udagram-reverseproxy:v1
            echo "-------- All images succesfully built----------"
            echo " ------- login in to hub--------"
            docker login -u mubbyrex -p $DOCKERPASS
            echo "-------------- Pushing images to dockerhub-------"
            docker push mubbyrex/udagram-api-feed:v1
            docker push mubbyrex/udagram-api-user:v1
            docker push mubbyrex/udagram-frontend:v1
            docker push mubbyrex/udagram-reverseproxy:v1
workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]
