apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  selector:
    matchLabels:
      service: backend-user
  replicas: 2
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
        - name: backend-user
          image: docker.io/mubbyrex/udagram-api-user:v3
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          envFrom:
            - secretRef:
                name: env-secret
                optional: false
            - configMapRef:
                name: my-configmap
                optional: false
