name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./udagram-frontend/Dockerfile
          push: true
          tags:  ${{ secrets.DOCKER_USERNAME }}/udagram-frontend:v1

#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Build the Docker image
#       run: |
#             docker build . --file udagram-frontend/Dockerfile --tag  ${{ secrets.DOCKER_USERNAME }}/udagram-frontend:v1
#             docker build . --file udagram-api-user/Dockerfile --tag  ${{ secrets.DOCKER_USERNAME }}/udagram-api-user:v1
#             docker build . --file udagram-api-feed/Dockerfile --tag  ${{ secrets.DOCKER_USERNAME }}/udagram-api-feed:v1
#             docker build . --file reverseproxy/Dockerfile --tag  ${{ secrets.DOCKER_USERNAME }}/reverseproxy:v1         
#     - name: Login to DockerHub
#       uses: docker/login-action@v2
#       with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#     - name: Build and push
#       uses: docker/build-push-action@v3
#       with:
#         file: 
#         context: .
#         push: true
          
    
